---
- name: Start nexus
  ansible.builtin.command: "{{ docker_compose_bin }} up --detach"
  args:
    chdir: "{{ nexus_home }}"
  register: start_result
  changed_when: start_result.rc == 0

- name: Stop nexus
  ansible.builtin.command: "{{ docker_compose_bin }} down"
  args:
    chdir: "{{ nexus_home }}"
  register: stop_result
  changed_when: stop_result.rc == 0

- name: Restart nexus
  ansible.builtin.shell: |
    {{ docker_compose_bin }} down
    {{ docker_compose_bin }} up --detach
  args:
    chdir: "{{ nexus_home }}"
  register: restart_result
  changed_when: restart_result.rc == 0
